name = "Jiafei_Cactus"
license = "MIT"
licenselink = "https://github.com/monkeyWzr/hugo-theme-cactus/blob/master/LICENSE"
description = "Hugo theme for personal blog. Forked from Hugo theme cactus created by @monkeyWzr."
homepage = "https://github.com/jiafeili/jiafei_cactus"
tags = ["blog", "responsive", "clean"]
features = ["mathjax", "customizable", "color"]
min_version = "0.48"

# If the theme has a single author
[author]
    name = "Jiafei Li"
    homepage = "https://github.com/jiafeili"

# If porting an existing theme
[original]
    author = "Pieter Robberechts"
    homepage = "https://github.com/probberechts"
    repo = "https://github.com/probberechts/hexo-theme-cactus"
